use crate::{EngineContext, GraphEngine, dispatch_tool};
use anyhow::Result;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::HashMap;
use std::collections::hash_map::DefaultHasher;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::time::Instant;
use uuid::Uuid;

/// --- AST Stability ---
/// Used to identify a symbol across code mutations while the global index is stale.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub struct SymbolAnchor {
    /// SHA-256 or semantic hash of the symbol's signature/header.
    pub semantic_hash: String,
    /// Absolute or relative path to the file.
    pub path: PathBuf,
    /// Language identifier (e.g., "rust").
    pub language: String,
}

impl SymbolAnchor {
    pub fn compute(signature: &str, path: &Path, language: &str) -> Self {
        let mut hasher = DefaultHasher::new();
        signature.hash(&mut hasher);
        let hash = format!("{:x}", hasher.finish());
        Self {
            semantic_hash: hash,
            path: path.to_path_buf(),
            language: language.to_string(),
        }
    }
}

/// --- REPLEngine (DSL AST) ---
/// Represents the high-level textual DSL generated by an LLM or typed by a human.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "type")]
pub enum DslNode {
    /// Atomic Tool Call: tool_name(args)
    Call {
        tool: String,
        args: serde_json::Value,
    },
    /// Transactional Block: atomic { ... }
    /// If any node fails or an abort is triggered, the entire block's shadow edits are rolled back.
    Atomic { nodes: Vec<DslNode> },
    /// Deterministic Termination: abort("reason")
    /// Triggers immediate rollback of the current atomic context.
    Abort { reason: String },
    /// Local Variable Assignment: let x = ...
    /// Used for scripting complex multi-step plans within the REPL.
    Assign {
        var: String,
        value: serde_json::Value,
    },
}

pub struct ReplState {
    pub variables: HashMap<String, Value>,
    pub active_plan: Option<Plan>,
}

impl Default for ReplState {
    fn default() -> Self {
        Self::new()
    }
}

impl ReplState {
    pub fn new() -> Self {
        Self {
            variables: HashMap::new(),
            active_plan: None,
        }
    }

    pub fn from_variables(variables: HashMap<String, Value>) -> Self {
        Self {
            variables,
            active_plan: None,
        }
    }

    pub fn resolve(&self, value: &Value) -> Value {
        match value {
            Value::String(s) => {
                // 1. Exact variable match (e.g., "$my_var")
                for (name, val) in &self.variables {
                    let var_pattern = format!("${}", name);
                    if *s == var_pattern {
                        return val.clone();
                    }
                }

                // 2. Complex path resolution (e.g., "$res[0].id")
                if let Some(stripped) = s.strip_prefix('$') {
                    let parts: Vec<&str> = stripped.split('.').collect();
                    if let Some(mut current) = self.variables.get(parts[0]) {
                        for &part in &parts[1..] {
                            if part.ends_with(']')
                                && let Some(idx_start) = part.find('[')
                            {
                                let field = &part[..idx_start];
                                let idx_str = &part[idx_start + 1..part.len() - 1];
                                if let Ok(idx) = idx_str.parse::<usize>() {
                                    if field.is_empty() {
                                        if let Some(v) = current.get(idx) {
                                            current = v;
                                        }
                                    } else if let Some(v) = current.get(field).and_then(|f| f.get(idx))
                                    {
                                        current = v;
                                    }
                                }
                            } else if let Some(v) = current.get(part) {
                                current = v;
                            }
                        }
                        return current.clone();
                    }
                }

                // 3. Substring interpolation (legacy fallback)
                let mut resolved = s.clone();
                for (name, val) in &self.variables {
                    let var_pattern = format!("${}", name);
                    if let Some(val_str) = val.as_str() {
                        resolved = resolved.replace(&var_pattern, val_str);
                    } else {
                        resolved = resolved.replace(&var_pattern, &val.to_string());
                    }
                }
                Value::String(resolved)
            }
            Value::Object(map) => {
                let mut new_map = serde_json::Map::new();
                for (k, v) in map {
                    new_map.insert(k.clone(), self.resolve(v));
                }
                Value::Object(new_map)
            }
            Value::Array(arr) => {
                let new_arr = arr.iter().map(|v| self.resolve(v)).collect();
                Value::Array(new_arr)
            }
            _ => value.clone(),
        }
    }
}

/// --- PlanEngine (The Execution Core) ---
pub type NodeId = Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Plan {
    pub id: Uuid,
    pub nodes: Vec<PlanNode>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanNode {
    pub id: NodeId,
    /// The specific tool operation or internal logic to execute.
    pub op: ToolOperation,
    /// Dependency resolution: IDs of nodes that MUST complete before this one starts.
    pub dependencies: Vec<IdOrTag>,
    /// Artifact Compaction: threshold (in bytes) before output is truncated and written to disk.
    pub output_limit: usize,
    /// Retry attempts for this node on failure.
    #[serde(default)]
    pub retry_limit: u8,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum IdOrTag {
    Id(NodeId),
    Tag(String),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ToolOperation {
    /// Standard MCP Tool Execution
    McpCall {
        tool: String,
        args: serde_json::Value,
    },
    /// Internal Engine Operations (e.g., recompute_graph, clear_shadow)
    Internal {
        command: String,
        params: serde_json::Value,
    },
}

pub struct PlanEngine {
    pub workspace_root: PathBuf,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PlanNodeRunState {
    node_id: NodeId,
    status: String,
    retries: u8,
    last_error: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PlanRunState {
    plan_id: Uuid,
    status: String,
    nodes: HashMap<String, PlanNodeRunState>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
struct FocusState {
    updated_at_secs: u64,
    active_tools: Vec<String>,
    active_uris: Vec<String>,
    active_symbols: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct CheckpointRecord {
    ts_secs: u64,
    event: String,
    plan_id: Uuid,
    node_id: Option<NodeId>,
    focus_state_path: String,
    plan_run_state_path: String,
    artifact_refs: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct FocusPrunePolicy {
    enabled: bool,
    max_distance: u8,
    max_uris: usize,
    #[serde(default)]
    override_keep_uris: Vec<String>,
}

impl Default for FocusPrunePolicy {
    fn default() -> Self {
        Self {
            enabled: false,
            max_distance: 2,
            max_uris: 128,
            override_keep_uris: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Default)]
struct FocusOverride {
    disable_prune: bool,
    max_distance: Option<u8>,
    keep_uris: Vec<String>,
}

impl PlanEngine {
    pub fn new(workspace_root: impl AsRef<Path>) -> Self {
        Self {
            workspace_root: std::fs::canonicalize(workspace_root.as_ref())
                .unwrap_or_else(|_| workspace_root.as_ref().to_path_buf()),
        }
    }

    fn plan_runs_dir(&self) -> PathBuf {
        self.workspace_root.join(".curd").join("plan_runs")
    }

    fn plan_run_path(&self, plan_id: Uuid) -> PathBuf {
        self.plan_runs_dir().join(format!("{}.json", plan_id))
    }

    fn persist_plan_state(&self, state: &PlanRunState) {
        let _ = fs::create_dir_all(self.plan_runs_dir());
        let _ = fs::write(
            self.plan_run_path(state.plan_id),
            serde_json::to_string_pretty(state).unwrap_or_else(|_| "{}".to_string()),
        );
    }

    fn checkpoints_dir(&self, plan_id: Uuid) -> PathBuf {
        self.workspace_root
            .join(".curd")
            .join("checkpoints")
            .join(plan_id.to_string())
    }

    fn checkpoint_file(&self, plan_id: Uuid, seq: usize, event: &str) -> PathBuf {
        self.checkpoints_dir(plan_id)
            .join(format!("{:04}_{}.json", seq, event))
    }

    fn write_checkpoint(
        &self,
        plan_id: Uuid,
        seq: usize,
        event: &str,
        node_id: Option<NodeId>,
        artifact_refs: &[String],
    ) {
        let _ = fs::create_dir_all(self.checkpoints_dir(plan_id));
        let ts_secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        let record = CheckpointRecord {
            ts_secs,
            event: event.to_string(),
            plan_id,
            node_id,
            focus_state_path: self
                .focus_state_path()
                .strip_prefix(&self.workspace_root)
                .unwrap_or(&self.focus_state_path())
                .to_string_lossy()
                .to_string(),
            plan_run_state_path: self
                .plan_run_path(plan_id)
                .strip_prefix(&self.workspace_root)
                .unwrap_or(&self.plan_run_path(plan_id))
                .to_string_lossy()
                .to_string(),
            artifact_refs: artifact_refs.to_vec(),
        };
        let _ = fs::write(
            self.checkpoint_file(plan_id, seq, event),
            serde_json::to_string_pretty(&record).unwrap_or_else(|_| "{}".to_string()),
        );
    }

    fn focus_state_path(&self) -> PathBuf {
        self.workspace_root.join(".curd").join("focus_state.json")
    }

    fn context_policy_path(&self) -> PathBuf {
        self.workspace_root
            .join(".curd")
            .join("context_policy.json")
    }

    fn load_focus_prune_policy(&self) -> FocusPrunePolicy {
        fs::read_to_string(self.context_policy_path())
            .ok()
            .and_then(|s| serde_json::from_str::<FocusPrunePolicy>(&s).ok())
            .unwrap_or_default()
    }

    fn parse_focus_override(args: &Value) -> FocusOverride {
        let mut out = FocusOverride::default();
        let Some(obj) = args.as_object() else {
            return out;
        };
        let Some(ov) = obj.get("_focus").and_then(|v| v.as_object()) else {
            return out;
        };
        out.disable_prune = ov
            .get("disable_prune")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        out.max_distance = ov
            .get("max_distance")
            .and_then(|v| v.as_u64())
            .map(|v| v as u8);
        if let Some(arr) = ov.get("keep_uris").and_then(|v| v.as_array()) {
            out.keep_uris = arr
                .iter()
                .filter_map(|v| v.as_str().map(|s| s.to_string()))
                .collect();
        }
        out
    }

    fn apply_focus_pruning(
        &self,
        focus: &mut FocusState,
        policy: &FocusPrunePolicy,
        override_cfg: &FocusOverride,
    ) {
        if !policy.enabled || override_cfg.disable_prune {
            return;
        }
        if focus.active_uris.len() <= policy.max_uris {
            return;
        }

        let anchor = match focus.active_uris.last() {
            Some(a) => a.clone(),
            None => return,
        };
        let distance = override_cfg.max_distance.unwrap_or(policy.max_distance);
        let ge = GraphEngine::new(&self.workspace_root);
        let graph = match ge.graph_with_depths(vec![anchor.clone()], distance, distance) {
            Ok(v) => v,
            Err(_) => return,
        };

        let mut keep: std::collections::HashSet<String> = std::collections::HashSet::new();
        keep.insert(anchor);
        for uri in &policy.override_keep_uris {
            keep.insert(uri.clone());
        }
        for uri in &override_cfg.keep_uris {
            keep.insert(uri.clone());
        }

        if let Some(arr) = graph.get("results").and_then(|v| v.as_array()) {
            for entry in arr {
                if let Some(fnid) = entry.get("function_id").and_then(|v| v.as_str()) {
                    keep.insert(fnid.to_string());
                }
                for side in ["up_levels", "down_levels"] {
                    if let Some(levels) = entry.get(side).and_then(|v| v.as_array()) {
                        for level in levels {
                            if let Some(nodes) = level.as_array() {
                                for n in nodes.iter().filter_map(|v| v.as_str()) {
                                    keep.insert(n.to_string());
                                }
                            }
                        }
                    }
                }
            }
        }

        focus.active_uris.retain(|u| {
            if !u.contains("::") {
                return true;
            }
            keep.contains(u)
        });
    }

    fn load_focus_state(&self) -> FocusState {
        fs::read_to_string(self.focus_state_path())
            .ok()
            .and_then(|s| serde_json::from_str::<FocusState>(&s).ok())
            .unwrap_or_default()
    }

    fn save_focus_state(&self, mut state: FocusState) {
        state.updated_at_secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        let _ = fs::create_dir_all(self.workspace_root.join(".curd"));
        let _ = fs::write(
            self.focus_state_path(),
            serde_json::to_string_pretty(&state).unwrap_or_else(|_| "{}".to_string()),
        );
    }

    fn push_unique_bounded(list: &mut Vec<String>, value: &str, max: usize) {
        if value.is_empty() {
            return;
        }
        if let Some(pos) = list.iter().position(|v| v == value) {
            list.remove(pos);
        }
        list.push(value.to_string());
        if list.len() > max {
            let extra = list.len() - max;
            list.drain(0..extra);
        }
    }

    fn harvest_focus_strings(value: &Value, uris: &mut Vec<String>, symbols: &mut Vec<String>) {
        match value {
            Value::String(s) => {
                if s.contains("::") {
                    uris.push(s.clone());
                    if let Some(sym) = s.rsplit("::").next()
                        && !sym.is_empty() {
                            symbols.push(sym.to_string());
                        }
                } else if s
                    .chars()
                    .all(|c| c.is_alphanumeric() || c == '_' || c == '-')
                {
                    symbols.push(s.clone());
                }
            }
            Value::Array(arr) => {
                for v in arr {
                    Self::harvest_focus_strings(v, uris, symbols);
                }
            }
            Value::Object(map) => {
                for (_k, v) in map {
                    Self::harvest_focus_strings(v, uris, symbols);
                }
            }
            _ => {}
        }
    }

    fn update_focus_from_tool(&self, tool: &str, args: &Value, result: Option<&Value>) {
        let mut focus = self.load_focus_state();
        let policy = self.load_focus_prune_policy();
        let override_cfg = Self::parse_focus_override(args);
        Self::push_unique_bounded(&mut focus.active_tools, tool, 64);

        let mut uris = Vec::new();
        let mut symbols = Vec::new();
        Self::harvest_focus_strings(args, &mut uris, &mut symbols);
        if let Some(res) = result {
            Self::harvest_focus_strings(res, &mut uris, &mut symbols);
        }

        for uri in uris {
            Self::push_unique_bounded(&mut focus.active_uris, &uri, 256);
        }
        for sym in symbols {
            Self::push_unique_bounded(&mut focus.active_symbols, &sym, 256);
        }

        self.apply_focus_pruning(&mut focus, &policy, &override_cfg);
        self.save_focus_state(focus);
    }

    fn artifact_dir(&self) -> PathBuf {
        self.workspace_root.join(".curd").join("artifacts")
    }

    fn compact_if_large(
        &self,
        scope: &str,
        id: Uuid,
        value: &Value,
        output_limit: usize,
    ) -> (Value, Option<PathBuf>, bool) {
        if output_limit == 0 {
            return (value.clone(), None, false);
        }
        let serialized = match serde_json::to_vec(value) {
            Ok(v) => v,
            Err(_) => return (value.clone(), None, false),
        };
        if serialized.len() <= output_limit {
            return (value.clone(), None, false);
        }

        let dir = self.artifact_dir().join(scope);
        let _ = fs::create_dir_all(&dir);
        let file = dir.join(format!("{}.json", id));
        let _ = fs::write(&file, &serialized);

        let compacted = json!({
            "status": "compacted",
            "summary": format!("Output exceeded {} bytes and was compacted.", output_limit),
            "artifact_path": file
                .strip_prefix(&self.workspace_root)
                .unwrap_or(&file)
                .to_string_lossy()
                .to_string()
        });
        (compacted, Some(file), true)
    }

    pub fn delete_plan(&self, plan_id: Uuid) -> Result<()> {
        let plan_path = self.workspace_root.join(".curd").join("plans").join(format!("{}.json", plan_id));
        if plan_path.exists() {
            fs::remove_file(plan_path)?;
        }
        let run_path = self.plan_run_path(plan_id);
        if run_path.exists() {
            fs::remove_file(run_path)?;
        }
        let checkpoint_dir = self.checkpoints_dir(plan_id);
        if checkpoint_dir.exists() {
            fs::remove_dir_all(checkpoint_dir)?;
        }
        Ok(())
    }

    pub fn get_plan(&self, plan_id: Uuid) -> Result<Plan> {
        let plan_path = self.workspace_root.join(".curd").join("plans").join(format!("{}.json", plan_id));
        if !plan_path.exists() {
            anyhow::bail!("Plan {} not found", plan_id);
        }
        let content = fs::read_to_string(plan_path)?;
        let plan: Plan = serde_json::from_str(&content)?;
        Ok(plan)
    }

    pub fn save_plan(&self, plan: &Plan) -> Result<()> {
        let plans_dir = self.workspace_root.join(".curd").join("plans");
        let _ = fs::create_dir_all(&plans_dir);
        let plan_path = plans_dir.join(format!("{}.json", plan.id));
        let content = serde_json::to_string_pretty(plan)?;
        fs::write(plan_path, content)?;
        Ok(())
    }

    pub fn register_plan(
        &self,
        plan: Plan,
        ctx: &EngineContext,
        state: &mut ReplState,
    ) -> Result<Value> {
        let plan_id = plan.id;
        let node_views: Vec<(NodeId, String)> = plan
            .nodes
            .iter()
            .map(|n| {
                let label = match &n.op {
                    ToolOperation::McpCall { tool, .. } => tool.clone(),
                    ToolOperation::Internal { command, .. } => format!("internal:{}", command),
                };
                (n.id, label)
            })
            .collect();

        // Persist plan to disk for human review/resumption
        let plans_dir = self.workspace_root.join(".curd").join("plans");
        let _ = fs::create_dir_all(&plans_dir);
        let plan_path = plans_dir.join(format!("{}.json", plan_id));
        let _ = fs::write(&plan_path, serde_json::to_string_pretty(&plan).unwrap_or_else(|_| "{}".to_string()));

        state.active_plan = Some(plan);

        let _ = ctx.tx_events.send(SystemEvent::PlanRegistered {
            plan_id,
            nodes: node_views,
        });

        Ok(
            json!({ 
                "status": "ok", 
                "plan_id": plan_id, 
                "node_count": state.active_plan.as_ref().unwrap().nodes.len(),
                "saved_to": plan_path.display().to_string()
            }),
        )
    }

    pub async fn execute_active_plan(
        &self,
        ctx: &EngineContext,
        state: &mut ReplState,
    ) -> Result<Value> {
        let plan = state
            .active_plan
            .take()
            .ok_or_else(|| anyhow::anyhow!("No active plan registered"))?;
        self.execute_plan(&plan, ctx, state).await
    }

    pub async fn execute_dsl(
        &self,
        nodes: &[DslNode],
        ctx: &EngineContext,
        state: &mut ReplState,
    ) -> Result<Value> {
        let mut results = Vec::new();

        let final_res = (async {
            for node in nodes {
                let start_time = Instant::now();
                match node {
                    DslNode::Call { tool, args } => {
                        let node_id = Uuid::new_v4();
                        let _ = ctx.tx_events.send(SystemEvent::NodeExecuting {
                            node_id,
                            tool: tool.clone(),
                        });

                        let resolved_args = state.resolve(args);
                        let res = dispatch_tool(tool, &resolved_args, ctx).await;
                        self.update_focus_from_tool(tool, &resolved_args, Some(&res));
                        // Fixed compaction threshold for DSL call outputs.
                        let (res_out, artifact_path, compacted) =
                            self.compact_if_large("dsl", node_id, &res, 64 * 1024);

                        let duration_ms = start_time.elapsed().as_millis() as u64;
                        let _ = ctx.tx_events.send(SystemEvent::NodeCompleted {
                            node_id,
                            duration_ms,
                            summary: if compacted {
                                format!("Tool {} finished (output compacted)", tool)
                            } else {
                                format!("Tool {} finished", tool)
                            },
                            artifact_path,
                        });

                        results.push(json!({ "tool": tool, "result": res_out }));
                    }
                    DslNode::Assign { var, value } => {
                        let resolved_val = state.resolve(value);
                        // If the value is a tool call, we execute it first
                        let final_val = if let Some(obj) = resolved_val.as_object()
                            && obj.contains_key("tool")
                            && obj.contains_key("args")
                        {
                            let t = obj.get("tool").unwrap().as_str().unwrap_or("");
                            let a = obj.get("args").unwrap();
                            let out = dispatch_tool(t, a, ctx).await;
                            self.update_focus_from_tool(t, a, Some(&out));
                            out
                        } else {
                            resolved_val
                        };
                        state.variables.insert(var.clone(), final_val.clone());
                        results.push(json!({ "assign": var, "value": final_val }));
                    }
                    DslNode::Atomic { nodes: nested } => {
                        // Start transaction (or savepoint if nested)
                        ctx.we.execute("begin")?;
                        match Box::pin(self.execute_dsl(nested, ctx, state)).await {
                            Ok(res) => {
                                // Commit savepoint
                                ctx.we.execute("commit")?;
                                let _ = ctx.tx_events.send(SystemEvent::PlanCommitted {
                                    session_id: ctx.session_id,
                                });
                                results.push(json!({ "atomic": "committed", "results": res }));
                            }
                            Err(e) => {
                                // Rollback savepoint
                                ctx.we.execute("rollback")?;
                                let _ = ctx.tx_events.send(SystemEvent::PlanAborted {
                                    plan_id: Uuid::nil(),
                                    reason: format!("Atomic rollback: {}", e),
                                });
                                return Err(anyhow::anyhow!(
                                    "Atomic block failed, rolled back: {}",
                                    e
                                ));
                            }
                        }
                    }
                    DslNode::Abort { reason } => {
                        let _ = ctx.tx_events.send(SystemEvent::PlanAborted {
                            plan_id: Uuid::nil(),
                            reason: reason.clone(),
                        });
                        return Err(anyhow::anyhow!("Plan aborted: {}", reason));
                    }
                }
            }
            Ok(Value::Array(results))
        })
        .await;

        match &final_res {
            Ok(v) => ctx
                .he
                .log(ctx.session_id, None, "dsl", json!(nodes), v.clone(), true, None),
            Err(e) => ctx.he.log(
                ctx.session_id,
                None,
                "dsl",
                json!(nodes),
                json!(null),
                false,
                Some(e.to_string()),
            ),
        }
        final_res
    }

    pub async fn execute_plan(
        &self,
        plan: &Plan,
        ctx: &EngineContext,
        state: &mut ReplState,
    ) -> Result<Value> {
        let mut checkpoint_seq: usize = 0;
        let mut artifact_refs: Vec<String> = Vec::new();
        let mut run_state = PlanRunState {
            plan_id: plan.id,
            status: "started".to_string(),
            nodes: HashMap::new(),
        };
        self.persist_plan_state(&run_state);
        self.write_checkpoint(
            plan.id,
            checkpoint_seq,
            "plan_started",
            None,
            &artifact_refs,
        );
        checkpoint_seq += 1;

        let _ = ctx.tx_events.send(SystemEvent::PlanStarted {
            plan_id: plan.id,
            total_nodes: plan.nodes.len(),
        });

        let mut graph = petgraph::graph::DiGraph::<usize, ()>::new();
        let mut node_indices = Vec::new();
        let mut id_map = HashMap::new();

        for (i, node) in plan.nodes.iter().enumerate() {
            let idx = graph.add_node(i);
            node_indices.push(idx);
            id_map.insert(node.id, idx);
        }

        for (i, node) in plan.nodes.iter().enumerate() {
            for dep in &node.dependencies {
                if let IdOrTag::Id(dep_id) = dep
                    && let Some(&dep_idx) = id_map.get(dep_id) {
                        graph.add_edge(dep_idx, node_indices[i], ());
                    }
            }
        }

        let sorted_indices = petgraph::algo::toposort(&graph, None)
            .map_err(|_| anyhow::anyhow!("Cycle detected in plan dependencies"))?;

        let mut results = HashMap::new();
        let final_res = (async {
            for idx in sorted_indices {
                let node_idx = graph[idx];
                let node = &plan.nodes[node_idx];
                let start_time = Instant::now();

                run_state.nodes.insert(
                    node.id.to_string(),
                    PlanNodeRunState {
                        node_id: node.id,
                        status: "executing".to_string(),
                        retries: 0,
                        last_error: None,
                    },
                );
                self.persist_plan_state(&run_state);

                let _ = ctx.tx_events.send(SystemEvent::NodeExecuting {
                    node_id: node.id,
                    tool: match &node.op {
                        ToolOperation::McpCall { tool, .. } => tool.clone(),
                        ToolOperation::Internal { command, .. } => format!("internal:{}", command),
                    },
                });

                let mut retries: u8 = 0;
                let res = loop {
                    let attempt_res: Result<Value> = match &node.op {
                        ToolOperation::McpCall { tool, args } => {
                            let resolved_args = state.resolve(args);
                            let out = Box::pin(dispatch_tool(tool, &resolved_args, ctx)).await;
                            self.update_focus_from_tool(tool, &resolved_args, Some(&out));
                            if out.get("error").is_some() {
                                Err(anyhow::anyhow!(
                                    "Tool '{}' returned error: {}",
                                    tool,
                                    out["error"]
                                ))
                            } else {
                                Ok(out)
                            }
                        }
                        ToolOperation::Internal { command, params } => match command.as_str() {
                            "recompute_graph" => {
                                let _ = crate::GraphEngine::new(&self.workspace_root);
                                Ok(json!({"status": "ok", "message": "Graph recomputed"}))
                            }
                            "clear_shadow" => {
                                ctx.we.execute("rollback")?;
                                Ok(json!({"status": "ok", "message": "Shadow workspace cleared"}))
                            }
                            "invalidate_index" => {
                                ctx.se.invalidate_index();
                                Ok(json!({"status": "ok", "message": "Symbol index invalidated"}))
                            }
                            "emit_marker" => {
                                let label = params
                                    .get("label")
                                    .and_then(|v| v.as_str())
                                    .unwrap_or("marker");
                                Ok(json!({"status": "ok", "marker": label}))
                            }
                            _ => Err(anyhow::anyhow!("Unknown internal command: {}", command)),
                        },
                    };

                    match attempt_res {
                        Ok(v) => break v,
                        Err(e) => {
                            if let Some(node_state) = run_state.nodes.get_mut(&node.id.to_string())
                            {
                                node_state.retries = retries;
                                node_state.last_error = Some(e.to_string());
                                node_state.status = "retrying".to_string();
                            }
                            self.persist_plan_state(&run_state);
                            if retries < node.retry_limit {
                                retries += 1;
                                continue;
                            }
                            if let Some(node_state) = run_state.nodes.get_mut(&node.id.to_string())
                            {
                                node_state.status = "failed".to_string();
                                node_state.retries = retries;
                                node_state.last_error = Some(e.to_string());
                            }
                            self.persist_plan_state(&run_state);
                            let _ = ctx.tx_events.send(SystemEvent::NodeFailed {
                                node_id: node.id,
                                error: e.to_string(),
                            });
                            return Err(e);
                        }
                    }
                };
                let (res_out, artifact_path, compacted) = self.compact_if_large(
                    &format!("plan/{}", plan.id),
                    node.id,
                    &res,
                    node.output_limit,
                );

                let duration_ms = start_time.elapsed().as_millis() as u64;
                if let Some(p) = &artifact_path {
                    artifact_refs.push(
                        p.strip_prefix(&self.workspace_root)
                            .unwrap_or(p)
                            .to_string_lossy()
                            .to_string(),
                    );
                }
                let _ = ctx.tx_events.send(SystemEvent::NodeCompleted {
                    node_id: node.id,
                    duration_ms,
                    summary: if compacted {
                        "Node finished (output compacted)".to_string()
                    } else {
                        "Node finished".to_string()
                    },
                    artifact_path,
                });

                if let Some(node_state) = run_state.nodes.get_mut(&node.id.to_string()) {
                    node_state.status = "completed".to_string();
                    node_state.retries = retries;
                }
                self.persist_plan_state(&run_state);
                self.write_checkpoint(
                    plan.id,
                    checkpoint_seq,
                    "node_completed",
                    Some(node.id),
                    &artifact_refs,
                );
                checkpoint_seq += 1;

                results.insert(node.id.to_string(), res_out);
            }
            Ok(json!(results))
        })
        .await;

        run_state.status = if final_res.is_ok() {
            "completed".to_string()
        } else {
            "failed".to_string()
        };
        self.persist_plan_state(&run_state);
        self.write_checkpoint(
            plan.id,
            checkpoint_seq,
            if final_res.is_ok() {
                "plan_completed"
            } else {
                "plan_failed"
            },
            None,
            &artifact_refs,
        );

        match &final_res {
            Ok(v) => ctx
                .he
                .log(ctx.session_id, None, "plan", json!(plan), v.clone(), true, None),
            Err(e) => ctx.he.log(
                ctx.session_id,
                None,
                "plan",
                json!(plan),
                json!(null),
                false,
                Some(e.to_string()),
            ),
        }
        final_res
    }
}

/// --- Observability (Ratatui TUI) ---
/// Broadcast payload for the SystemEvent channel.
#[derive(Debug, Clone, Serialize)]
pub enum SystemEvent {
    /// Dispatched when a plan is registered but not yet executed.
    PlanRegistered {
        plan_id: Uuid,
        nodes: Vec<(NodeId, String)>, // (ID, Label/Tool)
    },
    /// Dispatched when a new Plan starts execution.
    PlanStarted { plan_id: Uuid, total_nodes: usize },
    /// Dispatched when a specific Node starts.
    NodeExecuting { node_id: NodeId, tool: String },
    /// Dispatched on successful Node completion.
    NodeCompleted {
        node_id: NodeId,
        duration_ms: u64,
        summary: String,
        /// Path to the full artifact if it was compacted.
        artifact_path: Option<PathBuf>,
    },
    /// Dispatched on Node failure.
    NodeFailed { node_id: NodeId, error: String },
    /// Human-in-the-loop: A review tag was hit in the shadow workspace.
    ReviewRequired {
        file: PathBuf,
        line: usize,
        message: String,
    },
    /// Explicit abort triggered by the REPL or a Node guard.
    PlanAborted { plan_id: Uuid, reason: String },
    /// Final commit of a session to the main workspace.
    PlanCommitted { session_id: Uuid },
}
